### ISSUE TITLE
paper link

### ISSUE THREAD

**Issue by macknight** [ADG4050/Msc-Thesis#1]
Hi,
![image](https://github.com/ADG4050/Federated-Learning-Approach-towards-Smart-Energy-Meter-Dataset/assets/754293/4ff99d59-de41-4cc1-9e0e-2777986f86ed)

Is there any paper link for this project?

BR

**Comment by ADG4050** [comment]
Paper for this work is under publication, will share you once done

**Comment by ADG4050** [comment]
http://hdl.handle.net/2262/104085
