### ISSUE TITLE
GPU issue

### ISSUE THREAD

**Issue by macknight** [ADG4050/Msc-Thesis#10]
Hi,
May I know is it a MUST to have GPU and CUDA?
Can I just run the code on a normal laptop without GPU and CUDA?

![image](https://github.com/ADG4050/Federated-Learning-Approach-towards-Smart-Energy-Meter-Dataset/assets/754293/5bfc1800-c40f-4c7c-b1d4-1607c1135e78)

BR

**Comment by ADG4050** [comment]
Yes it can be run without CUDA, try it in Collab
