### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by macknight** [ADG4050/Msc-Thesis#2]
Hi,
![image](https://github.com/ADG4050/Federated-Learning-Approach-towards-Smart-Energy-Meter-Dataset/assets/754293/ee19c0b1-165f-4c7a-b804-27d38072f7b0)

Is it OK to run the model on laptop rather than Arduino?
BR

**Comment by ADG4050** [comment]
This is just a simple code to check the energy consumption that will be incurred when we run in an arduino uno platform to prove the effectiveness of lightweight models. Yes any arduino simulator can run this file, however to check the energy consumption you might need some sort of energy measurement device.
