### ISSUE TITLE
cluster-i

### ISSUE THREAD

**Issue by macknight** [ADG4050/Msc-Thesis#4]
Hi,
![image](https://github.com/ADG4050/Federated-Learning-Approach-towards-Smart-Energy-Meter-Dataset/assets/754293/e1d738dd-0649-41ca-acb0-cdc8bfd1e9fc)

May I know what does this mean by the connections between households and cluster-i?

Besides, the README doesn't explicitly mention about clusters. Do clusters are used to preprocess raw data? And what's the purpose of using different cluster-i? like cluster4, cluster8?

![image](https://github.com/ADG4050/Federated-Learning-Approach-towards-Smart-Energy-Meter-Dataset/assets/754293/b5bee744-112c-4251-8d8c-d3df3f4fa9b2)

BR

**Comment by ADG4050** [comment]
Cluttering is done so that we perform federated learning in a group having similar consumption to prevent bias in prediction emulating real life scenario where we expect in a locality having houses of similar consumption.
