### ISSUE TITLE
how to run each code files?

### ISSUE THREAD

**Issue by macknight** [ADG4050/Msc-Thesis#5]
Hi,
There are 5 related code files for federated learning.
Then what's the relationship between Short_term_fc_custom_LF.ipynb and Customized_tff_funcitonalities.ipynb?
Any sequence I should run this files?

BR

**Comment by ADG4050** [comment]
Customized_tff_funcitonalities.ipynb, contains where we check whether the federated averaging process works using tensor flow federated functions by using customised functions, this is just a file to show that the inbuilt federated averaging process works. 

Other file is the prediction work file weekly, daily or monthly as per requirement.
