### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by macknight** [ADG4050/Msc-Thesis#6]
Hi,
https://www.kaggle.com/datasets/jeanmidev/smart-meters-in-london?select=daily_dataset

![image](https://github.com/ADG4050/Federated-Learning-Approach-towards-Smart-Energy-Meter-Dataset/assets/754293/02980d23-8890-499c-a0a7-d3eb9a851284)

But the data looks different in the code?
![image](https://github.com/ADG4050/Federated-Learning-Approach-towards-Smart-Energy-Meter-Dataset/assets/754293/8362fa2c-6a8e-4a5f-b8e5-cefc20232d7c)

where does 'LCL-FullData\CC_LCL-FullData.csv' come from?

BR

**Comment by ADG4050** [comment]
The actual original dataset is based on https://data.london.gov.uk/dataset/smartmeter-energy-use-data-in-london-households (this is the original source of dataset), the dataset in kaggle is derived and worked upon from this original source.
