### ISSUE TITLE
mae issue

### ISSUE THREAD

**Issue by macknight** [ADG4050/Msc-Thesis#7]
Hi,
![image](https://github.com/ADG4050/Federated-Learning-Approach-towards-Smart-Energy-Meter-Dataset/assets/754293/52e83e78-46f3-4d06-9a49-1692002b3255)

May I know where these floating numbers in the mae list come from? Why does each have 20 elements?

Is it because the NUM_ROUNDS = 21 withouth the first round? that's 21-1 = 20.

BR

**Comment by ADG4050** [comment]
These are training data obtained for graph visualization, yes 20 data for 20 federated rounds
