### ISSUE TITLE
evaluation issue

### ISSUE THREAD

**Issue by macknight** [ADG4050/Msc-Thesis#8]
Hi,
![image](https://github.com/ADG4050/Federated-Learning-Approach-towards-Smart-Energy-Meter-Dataset/assets/754293/d7e6cba0-9396-4ca1-a20b-16d7c6a6818f)

Why is there drawing pictures for mae before the comment "FEDERATED EVALUATION"? shouldn't they be after the comment "FEDERATED EVALUATION"?

BR

**Comment by ADG4050** [comment]
For Training loss evaluation
